import type { Metadata } from 'next'
import { Inter, Noto_Sans_Arabic, Tajawal } from "next/font/google";
import RootProvider from "../utils/root-provider";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const AR_Tajawal = Tajawal({
  subsets: ["arabic"],
  weight: "700",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html dir="rtl" lang="ar">
      <body className={AR_Tajawal.className}>
        <RootProvider>
          <main>{children}</main>
        </RootProvider>
      </body>
    </html>
  );
}
